/**
 * Cross-checks against independent, third-party calendar implementations
 * (Python's `convertdate` and `lunardate`), via fixtures generated by
 * `scripts/generate_fixtures.py`. See that script's docstring for how to
 * regenerate. This is what "How this is computed" / "Accuracy" claims in
 * the README point to as evidence, not just our own round-trip tests.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { chineseFromJD, chineseNewYear } from '../src/lib/chinese.js';
import * as coptic from '../src/lib/coptic.js';
import { gregorianToJD, julianToJD } from '../src/lib/core/jd.js';
import * as hebrew from '../src/lib/hebrew.js';
import * as islamic from '../src/lib/islamic.js';
import * as maya from '../src/lib/maya.js';

const fixturesDir = fileURLToPath(new URL('./fixtures/', import.meta.url));
function loadFixture<T>(name: string): T {
  return JSON.parse(readFileSync(`${fixturesDir}${name}`, 'utf-8')) as T;
}

describe('oracle: gregorian/julian -> JD (convertdate)', () => {
  const gregorian =
    loadFixture<Array<{ year: number; month: number; day: number; jd: number }>>(
      'gregorian-jd.json',
    );
  it(`matches convertdate on ${gregorian.length} Gregorian dates`, () => {
    for (const c of gregorian) {
      expect(gregorianToJD(c.year, c.month, c.day)).toBeCloseTo(c.jd, 6);
    }
  });

  const julian =
    loadFixture<Array<{ year: number; month: number; day: number; jd: number }>>('julian-jd.json');
  it(`matches convertdate on ${julian.length} Julian dates`, () => {
    for (const c of julian) {
      expect(julianToJD(c.year, c.month, c.day)).toBeCloseTo(c.jd, 6);
    }
  });
});

describe('oracle: Hebrew calendar (convertdate)', () => {
  const fixtures =
    loadFixture<Array<{ jd: number; hebrew: [number, number, number] }>>('hebrew.json');
  it(`matches convertdate on ${fixtures.length} dates`, () => {
    let mismatches = 0;
    for (const f of fixtures) {
      const d = hebrew.fromJD(f.jd);
      if (d.year !== f.hebrew[0] || d.month !== f.hebrew[1] || d.day !== f.hebrew[2]) {
        mismatches++;
      }
    }
    expect(mismatches, `${mismatches}/${fixtures.length} mismatches`).toBe(0);
  });
});

describe('oracle: Islamic tabular calendar (convertdate)', () => {
  const fixtures =
    loadFixture<Array<{ jd: number; islamic: [number, number, number] }>>('islamic.json');
  it(`matches convertdate on ${fixtures.length} dates`, () => {
    let mismatches = 0;
    for (const f of fixtures) {
      const d = islamic.fromJD(f.jd);
      if (d.year !== f.islamic[0] || d.month !== f.islamic[1] || d.day !== f.islamic[2]) {
        mismatches++;
      }
    }
    expect(mismatches, `${mismatches}/${fixtures.length} mismatches`).toBe(0);
  });
});

describe('oracle: Coptic calendar (convertdate)', () => {
  const fixtures =
    loadFixture<Array<{ jd: number; coptic: [number, number, number] }>>('coptic.json');
  it(`matches convertdate on ${fixtures.length} dates`, () => {
    let mismatches = 0;
    for (const f of fixtures) {
      const d = coptic.copticFromJD(f.jd);
      if (d.year !== f.coptic[0] || d.month !== f.coptic[1] || d.day !== f.coptic[2]) {
        mismatches++;
      }
    }
    expect(mismatches, `${mismatches}/${fixtures.length} mismatches`).toBe(0);
  });
});

describe('oracle: Maya Long Count (convertdate)', () => {
  const fixtures =
    loadFixture<
      Array<{
        jd: number;
        longCount: { baktun: number; katun: number; tun: number; winal: number; kin: number };
      }>
    >('mayan.json');
  it(`matches convertdate on ${fixtures.length} dates`, () => {
    let mismatches = 0;
    for (const f of fixtures) {
      const lc = maya.longCountFromJD(f.jd);
      const same =
        lc.baktun === f.longCount.baktun &&
        lc.katun === f.longCount.katun &&
        lc.tun === f.longCount.tun &&
        lc.winal === f.longCount.winal &&
        lc.kin === f.longCount.kin;
      if (!same) mismatches++;
    }
    expect(mismatches, `${mismatches}/${fixtures.length} mismatches`).toBe(0);
  });
});

describe('oracle: Chinese New Year 2000-2030 (lunardate)', () => {
  const fixtures =
    loadFixture<Array<{ chineseYear: number; gregorian: [number, number, number] }>>(
      'chinese-new-year.json',
    );
  it('matches lunardate to within 1 day for every year 2000-2030', () => {
    // Our astronomical root-finder and lunardate's own tabulated ephemeris
    // both target "the new moon nearest China Standard Time midnight"; a
    // 1-day tolerance absorbs legitimate differences in low-precision Sun/
    // Moon longitude formulas landing a new moon just before/after local
    // midnight. Document the actual observed max error, don't just assert.
    let maxErrDays = 0;
    for (const f of fixtures) {
      const ourJD = chineseNewYear(f.chineseYear);
      const oracleJD = gregorianToJD(f.gregorian[0], f.gregorian[1], f.gregorian[2]);
      maxErrDays = Math.max(maxErrDays, Math.abs(ourJD - oracleJD));
    }
    // eslint-disable-next-line no-console
    console.log(
      `Chinese New Year: max deviation from lunardate over 2000-2030 = ${maxErrDays.toFixed(3)} days`,
    );
    expect(maxErrDays).toBeLessThan(1);
  });
});

describe('oracle: Chinese lunar month/leap-month boundaries 2000-2035 (lunardate)', () => {
  // 447 first-of-month transitions, including several real leap months where
  // a solar term and the bounding new moon land on the same civil day (e.g.
  // 2014's leap 9th month, 2020's leap 4th month - see the comment on
  // zhongqiBucketForLocalDay in src/lib/chinese.ts for how those are
  // resolved). We do not require a perfect match: two categories of
  // disagreement are expected and documented in docs/CALENDARS.md rather
  // than chased away -
  //  1. Sub-day timing: our root-found new moons can land up to ~1 day from
  //     the reference's tabulated ones (measured earlier in this file, in
  //     the Chinese New Year check), so a boundary date right at a month
  //     transition can occasionally disagree by one day's worth of month
  //     number.
  //  2. 2033 is a *genuinely disputed* year in real-world Chinese calendar
  //     implementations: its winter-solstice cycle has two candidate
  //     zhongqi-less months close together, and different published
  //     algorithms (and different real Chinese/Hong Kong/Taiwanese
  //     almanacs) place the leap month differently (commonly leap7 vs
  //     leap11). Disagreeing with one third-party oracle on this specific
  //     year is not evidence of a bug.
  const fixtures = loadFixture<
    Array<{
      gregorian: [number, number, number];
      chineseYear: number;
      chineseMonth: number;
      isLeapMonth: boolean;
    }>
  >('chinese-month-boundaries.json');
  it(`agrees with lunardate's month/leap-month label on at least 98% of ${fixtures.length} boundary dates`, () => {
    let mismatches = 0;
    const details: string[] = [];
    for (const f of fixtures) {
      const jd = gregorianToJD(...f.gregorian);
      const ours = chineseFromJD(jd);
      const same = ours.month === f.chineseMonth && ours.isLeapMonth === f.isLeapMonth;
      if (!same) {
        mismatches++;
        details.push(
          `${f.gregorian.join('-')}: oracle month ${f.chineseMonth}${f.isLeapMonth ? ' (leap)' : ''}, ours ${ours.month}${ours.isLeapMonth ? ' (leap)' : ''}`,
        );
      }
    }
    const rate = mismatches / fixtures.length;
    // eslint-disable-next-line no-console
    console.log(
      `Chinese month boundaries: ${mismatches}/${fixtures.length} mismatches:\n${details.join('\n')}`,
    );
    expect(rate, `mismatch rate ${(rate * 100).toFixed(1)}%`).toBeLessThan(0.02);
  });
});
