/**
 * Cross-checks against independent, third-party calendar implementations
 * (Python's `convertdate` and `lunardate`), via fixtures generated by
 * `scripts/generate_fixtures.py`. See that script's docstring for how to
 * regenerate. This is what "How this is computed" / "Accuracy" claims in
 * the README point to as evidence, not just our own round-trip tests.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { chineseFromJD, chineseNewYear } from '../src/lib/chinese.js';
import * as coptic from '../src/lib/coptic.js';
import { gregorianToJD, julianToJD } from '../src/lib/core/jd.js';
import * as hebrew from '../src/lib/hebrew.js';
import * as islamic from '../src/lib/islamic.js';
import * as maya from '../src/lib/maya.js';

const fixturesDir = fileURLToPath(new URL('./fixtures/', import.meta.url));
function loadFixture<T>(name: string): T {
  return JSON.parse(readFileSync(`${fixturesDir}${name}`, 'utf-8')) as T;
}

describe('oracle: gregorian/julian -> JD (convertdate)', () => {
  const gregorian =
    loadFixture<Array<{ year: number; month: number; day: number; jd: number }>>(
      'gregorian-jd.json',
    );
  it(`matches convertdate on ${gregorian.length} Gregorian dates`, () => {
    for (const c of gregorian) {
      expect(gregorianToJD(c.year, c.month, c.day)).toBeCloseTo(c.jd, 6);
    }
  });

  const julian =
    loadFixture<Array<{ year: number; month: number; day: number; jd: number }>>('julian-jd.json');
  it(`matches convertdate on ${julian.length} Julian dates`, () => {
    for (const c of julian) {
      expect(julianToJD(c.year, c.month, c.day)).toBeCloseTo(c.jd, 6);
    }
  });
});

describe('oracle: Hebrew calendar (convertdate)', () => {
  const fixtures =
    loadFixture<Array<{ jd: number; hebrew: [number, number, number] }>>('hebrew.json');
  it(`matches convertdate on ${fixtures.length} dates`, () => {
    let mismatches = 0;
    for (const f of fixtures) {
      const d = hebrew.fromJD(f.jd);
      if (d.year !== f.hebrew[0] || d.month !== f.hebrew[1] || d.day !== f.hebrew[2]) {
        mismatches++;
      }
    }
    expect(mismatches, `${mismatches}/${fixtures.length} mismatches`).toBe(0);
  });
});

describe('oracle: Islamic tabular calendar (convertdate)', () => {
  const fixtures =
    loadFixture<Array<{ jd: number; islamic: [number, number, number] }>>('islamic.json');
  it(`matches convertdate on ${fixtures.length} dates`, () => {
    let mismatches = 0;
    for (const f of fixtures) {
      const d = islamic.fromJD(f.jd);
      if (d.year !== f.islamic[0] || d.month !== f.islamic[1] || d.day !== f.islamic[2]) {
        mismatches++;
      }
    }
    expect(mismatches, `${mismatches}/${fixtures.length} mismatches`).toBe(0);
  });
});

describe('oracle: Coptic calendar (convertdate)', () => {
  const fixtures =
    loadFixture<Array<{ jd: number; coptic: [number, number, number] }>>('coptic.json');
  it(`matches convertdate on ${fixtures.length} dates`, () => {
    let mismatches = 0;
    for (const f of fixtures) {
      const d = coptic.copticFromJD(f.jd);
      if (d.year !== f.coptic[0] || d.month !== f.coptic[1] || d.day !== f.coptic[2]) {
        mismatches++;
      }
    }
    expect(mismatches, `${mismatches}/${fixtures.length} mismatches`).toBe(0);
  });
});

describe('oracle: Maya Long Count (convertdate)', () => {
  const fixtures =
    loadFixture<
      Array<{
        jd: number;
        longCount: { baktun: number; katun: number; tun: number; winal: number; kin: number };
      }>
    >('mayan.json');
  it(`matches convertdate on ${fixtures.length} dates`, () => {
    let mismatches = 0;
    for (const f of fixtures) {
      const lc = maya.longCountFromJD(f.jd);
      const same =
        lc.baktun === f.longCount.baktun &&
        lc.katun === f.longCount.katun &&
        lc.tun === f.longCount.tun &&
        lc.winal === f.longCount.winal &&
        lc.kin === f.longCount.kin;
      if (!same) mismatches++;
    }
    expect(mismatches, `${mismatches}/${fixtures.length} mismatches`).toBe(0);
  });
});

describe('oracle: Chinese New Year 2000-2030 (lunardate)', () => {
  const fixtures =
    loadFixture<Array<{ chineseYear: number; gregorian: [number, number, number] }>>(
      'chinese-new-year.json',
    );
  it('matches the civil date exactly, including the UTC+8 day boundary', () => {
    for (const f of fixtures) {
      const midnight = gregorianToJD(...f.gregorian) - 1 / 3;
      expect(chineseNewYear(f.chineseYear), `year ${f.chineseYear}`).toBe(midnight);
      expect(chineseFromJD(midnight)).toMatchObject({
        yearNumber: f.chineseYear,
        month: 1,
        day: 1,
      });
      expect(chineseFromJD(midnight - 1 / 86400).yearNumber).toBe(f.chineseYear - 1);
    }
  });
});

describe('oracle: Chinese lunar month boundaries 2000-2035 (lunardate)', () => {
  const fixtures = loadFixture<
    Array<{
      gregorian: [number, number, number];
      chineseYear: number;
      chineseMonth: number;
      chineseDay: number;
      isLeapMonth: boolean;
    }>
  >('chinese-month-boundaries.json');
  it(`matches all ${fixtures.length} reference dates throughout the local civil day`, () => {
    for (const f of fixtures) {
      const midnight = gregorianToJD(...f.gregorian) - 1 / 3;
      for (const offset of [0, 0.5, 1 - 1 / 86400]) {
        expect(
          chineseFromJD(midnight + offset),
          `${f.gregorian.join('-')}, offset ${offset}`,
        ).toMatchObject({
          yearNumber: f.chineseYear,
          month: f.chineseMonth,
          isLeapMonth: f.isLeapMonth,
          day: f.chineseDay,
        });
      }
      // The first row starts the fixture's range on 1 January 2000; it is
      // lunar day 25. The remaining 446 rows are actual month starts.
      if (f.chineseDay === 1)
        expect(chineseFromJD(midnight - 1 / 86400).day).toBeGreaterThanOrEqual(29);
    }
  });
});
